# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cIYFzAYai4rlkPaONyI9JcGM6DvOUuY
"""

!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install seaborn
!pip install scikit-learn

import numpy as np
import  pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

!pip install -q \
numpy \
pandas \
matplotlib \
seaborn \
scipy \
scikit-learn \
statsmodels \
pingouin \
plotly \
kaleido \
ydata-profiling \
dtale \
skimpy \
missingno \
openpyxl \
jupyter \
ipykernel

!pip install -q numpy pandas matplotlib seaborn scipy scikit-learn statsmodels pingouin plotly kaleido ydata-profiling dtale skimpy missingno openpyxl

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

from ydata_profiling import ProfileReport
import dtale
from skimpy import skim
import missingno as msno

from scipy import stats
from scipy.stats import (
    pearsonr,
    spearmanr,
    ttest_rel,
    ttest_ind,
    mannwhitneyu,
    wilcoxon,
    kruskal
)

import statsmodels.api as sm
import statsmodels.formula.api as smf

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

import openpyxl

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

sns.set_theme(style="whitegrid")

print("✅ All required libraries are ready!")

import pandas as pd
data=pd.read_excel("/content/data-processmental health.xlsx")

data.head(10)

print("Shape:")
print(data.shape)

print("\nColumns:")
print(data.columns.tolist())

print("\nFirst 5 rows:")
display(data.head())

print("\nLast 5 rows:")
display(data.tail())

print("\nData types:")
print(data.dtypes)

import dtale

d = dtale.show(data)
d

from ydata_profiling import ProfileReport

profile = ProfileReport(data, title="Social Media Behavioral Dataset Report")
profile



import kagglehub

# Download latest version
path = kagglehub.dataset_download("emirhanai/social-media-usage-and-emotional-well-being")

print("Path to dataset files:", path)

# RQ1: How does daily usage time vary across platforms and demographics?

"""RQ1: How does daily usage time vary across platforms and demographics?
RQ2: Is higher daily usage time associated with a particular dominant emotion (e.g., anxiety, boredom)?
RQ3: Do engagement behaviors (posting, likes/comments received, messaging) differ by platform?
RQ4: Are there distinct "usage profiles" among users (via clustering) that map onto different emotional states?
RQ5: Which variables correlate most strongly with usage time and with emotional state?**bold text**
"""

# Core
import pandas as pd
import numpy as np

# Automated EDA
from ydata_profiling import ProfileReport
import dtale
from skimpy import skim
import missingno as msno

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# Statistics
from scipy import stats
from scipy.stats import spearmanr, chi2_contingency, kruskal, mannwhitneyu, f_oneway
import pingouin as pg
import statsmodels.api as sm
import statsmodels.formula.api as smf

# Machine Learning
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Excel
import openpyxl

pd.set_option("display.max_columns", None)
sns.set_style("whitegrid")
print("done")

import pandas as pd

# Load with bad-line tolerance for val.csv's malformed row
train = pd.read_csv("/content/train.csv")
test = pd.read_csv("/content/test.csv")
val = pd.read_csv("/content/val.csv", on_bad_lines="skip", engine="python")

# 1. Remove the AI-generated leak row in train.csv (Age is non-numeric AND User_ID is non-numeric)
train = train[pd.to_numeric(train["User_ID"], errors="coerce").notna()].copy()

# 2. Fix the 77 column-shifted rows in train.csv (Age column holding Gender text)
shifted_mask = pd.to_numeric(train["Age"], errors="coerce").isna()
print("Rows still shifted before fix:", shifted_mask.sum())

cols = train.columns.tolist()
# shift these rows' values one column to the right, recover User_ID as unknown
train.loc[shifted_mask, cols[1:]] = train.loc[shifted_mask, cols[:-1]].values
train.loc[shifted_mask, "User_ID"] = pd.NA

print("Rows still shifted after fix:", pd.to_numeric(train.loc[shifted_mask, "Age"], errors="coerce").isna().sum())

# Re-check everyone
for name, df in [("train", train), ("test", test), ("val", val)]:
    print(f"\n=== {name} ===")
    print("Shape:", df.shape)
    print("Nulls:\n", df.isnull().sum())
    print("Duplicates:", df.duplicated().sum())

# Combine for EDA (add a source tag so we can split back later if needed)
train["split"] = "train"
test["split"] = "test"
val["split"] = "val"
df = pd.concat([train, test, val], ignore_index=True)

print("Combined shape:", df.shape)
df.head()

# Automated EDA #1 — YData Profiling (comprehensive HTML report)
from ydata_profiling import ProfileReport
profile = ProfileReport(df, title="Social Media & Emotion Dataset Report", minimal=True)
profile.to_notebook_iframe()

# Automated EDA #2 — Skimpy (fast console summary)
from skimpy import skim
skim(df)

# Automated EDA #3 — Missingno (visualize missing pattern)
import missingno as msno
msno.matrix(df)
plt.show()

# missing values in user id dont effect the data so leavve it begibbndf

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

sns.histplot(df["Age"], bins=15, kde=True, ax=axes[0])
axes[0].set_title("Age Distribution")

sns.countplot(data=df, x="Gender", ax=axes[1], order=df["Gender"].value_counts().index)
axes[1].set_title("Gender Distribution")

sns.countplot(data=df, y="Platform", ax=axes[2], order=df["Platform"].value_counts().index)
axes[2].set_title("Platform Distribution")

plt.tight_layout()
plt.show()

print(df["Age"].describe())
print(df["Gender"].value_counts(normalize=True) * 100)
print(df["Platform"].value_counts(normalize=True) * 100)

usage_cols = ["Daily_Usage_Time (minutes)", "Posts_Per_Day",
              "Likes_Received_Per_Day", "Comments_Received_Per_Day",
              "Messages_Sent_Per_Day"]

# Convert usage columns to numeric, coercing errors to NaN
for col_name in usage_cols:
    df[col_name] = pd.to_numeric(df[col_name], errors='coerce')

# Drop rows with NaN values in usage_cols for plotting to avoid errors
df_cleaned_usage = df.dropna(subset=usage_cols)

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.flatten()
for i, col in enumerate(usage_cols):
    # Plot using the cleaned DataFrame
    sns.histplot(df_cleaned_usage[col], bins=20, kde=True, ax=axes[i])
    axes[i].set_title(f"{col} — skew={df_cleaned_usage[col].skew():.2f}")
plt.tight_layout()
plt.show()

# Describe the original df, which will now show NaNs if any were coerced
df[usage_cols].describe()

# Platform-wise usage comparison
plt.figure(figsize=(10,5))
sns.boxplot(data=df, x="Platform", y="Daily_Usage_Time (minutes)")
plt.title("Daily Usage Time by Platform")
plt.xticks(rotation=30)
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(data=df, x="Dominant_Emotion",
              order=df["Dominant_Emotion"].value_counts().index)
plt.title("Distribution of Dominant Emotion")
plt.xticks(rotation=30)
plt.show()

# Cross-tab: Platform vs Emotion
cross_tab = pd.crosstab(df["Platform"], df["Dominant_Emotion"], normalize="index") * 100
print(cross_tab.round(1))

plt.figure(figsize=(10,6))
sns.heatmap(cross_tab, annot=True, fmt=".1f", cmap="YlOrRd")
plt.title("% of Emotion within each Platform")
plt.show()

plt.figure(figsize=(10,6))
sns.boxplot(data=df, x="Dominant_Emotion", y="Daily_Usage_Time (minutes)",
            order=df.groupby("Dominant_Emotion")["Daily_Usage_Time (minutes)"].median().sort_values().index)
plt.title("Usage Time across Emotion Groups")
plt.xticks(rotation=30)
plt.show()

from scipy.stats import spearmanr

corr_matrix = df[usage_cols].corr(method="spearman")
plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", vmin=-1, vmax=1)
plt.title("Spearman Correlation — Usage Variables")
plt.show()

from scipy.stats import kruskal, chi2_contingency

# Test 1: Kruskal-Wallis — does usage time differ significantly across emotion groups?
# (Kruskal-Wallis chosen over ANOVA because usage time is skewed, not normal)
groups = [g["Daily_Usage_Time (minutes)"].dropna().values
          for _, g in df.groupby("Dominant_Emotion")]
h_stat, p_val = kruskal(*groups)
print(f"Kruskal-Wallis: H={h_stat:.3f}, p={p_val:.4f}")

# Test 2: Chi-square — is Platform associated with Emotion?
contingency = pd.crosstab(df["Platform"], df["Dominant_Emotion"])
chi2, p_chi, dof, expected = chi2_contingency(contingency)
print(f"Chi-square: chi2={chi2:.3f}, dof={dof}, p={p_chi:.4f}")

import pingouin as pg

# Effect size for Kruskal-Wallis: epsilon-squared
n = len(df)
epsilon_sq = h_stat / (n - 1)
print(f"Epsilon-squared (Kruskal-Wallis effect size): {epsilon_sq:.4f}")
# Rough guide: <0.01 negligible, 0.01-0.08 small, 0.08-0.26 medium, >0.26 large

# Effect size for Chi-square: Cramér's V
cramers_v = pg.chi2_independence(data=df, x="Platform", y="Dominant_Emotion")[2]["cramer"].values[0]
print(f"Cramér's V (Platform vs Emotion): {cramers_v:.4f}")
# Rough guide: <0.1 negligible, 0.1-0.3 small, 0.3-0.5 medium, >0.5 large

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Standardize usage variables (required before PCA/KMeans — different units/scales)
X = df[usage_cols].dropna()
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# PCA for dimensionality reduction / visualization
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
print("Explained variance ratio:", pca.explained_variance_ratio_)

# Find optimal k using silhouette score (test k=2 to 6)
sil_scores = {}
for k in range(2, 7):
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(X_scaled)
    sil_scores[k] = silhouette_score(X_scaled, labels)
    print(f"k={k}: silhouette={sil_scores[k]:.4f}")

best_k = max(sil_scores, key=sil_scores.get)
print(f"\nBest k = {best_k}")

# Fit final KMeans with best k
kmeans = KMeans(n_clusters=best_k, random_state=42, n_init=10)
df_clustered = X.copy()
df_clustered["cluster"] = kmeans.fit_predict(X_scaled)

# Visualize clusters on PCA plane
plt.figure(figsize=(8,6))
sns.scatterplot(x=X_pca[:,0], y=X_pca[:,1], hue=df_clustered["cluster"], palette="Set2")
plt.title(f"User Clusters (k={best_k}) on PCA Components")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

# Profile each cluster — what makes it distinct?
print(df_clustered.groupby("cluster")[usage_cols].mean().round(1))

print("""
KEY FINDINGS (fill in with real numbers from your output above):
1. Sample: N=___, mostly aged ___, platform distribution: ___
2. Usage time was [right-skewed], median = ___ minutes/day
3. Dominant emotion distribution: ___
4. Usage time [was/was not] significantly associated with emotion (p=___, effect size ε²=___)
5. Platform [was/was not] significantly associated with emotion (p=___, Cramér's V=___)
6. PCA/KMeans revealed ___ distinct usage clusters, characterized by: ___

LIMITATIONS:
- This dataset shows strong evidence of synthetic/AI generation (a literal AI-assistant
  text fragment was found embedded in the raw file), so findings here are for
  METHODOLOGY PRACTICE ONLY and are not generalizable to real populations.
- No causal claims can be made — this is cross-sectional, non-experimental data.
- Self-reported/generated "Dominant_Emotion" has no validated measurement instrument.
- Sample is not Pakistan-specific and does not measure the cognitive/behavioral
  constructs (concentration, patience, deep work) central to the actual research aim.
""")

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import (accuracy_score, classification_report,
                              confusion_matrix, f1_score)
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# ---- 1. Robust Cleaning of Categorical and Numeric Columns ----
# Define valid categories to filter out shifted data/garbage
valid_platforms = ['Instagram', 'Facebook', 'Twitter', 'LinkedIn', 'Snapchat', 'Telegram', 'Whatsapp']
valid_genders = ['Female', 'Male', 'Non-binary']
valid_emotions = ['Happiness', 'Anger', 'Neutral', 'Anxiety', 'Boredom', 'Sadness']

def clean_dataframe(target_df):
    d = target_df.copy()
    # Ensure usage and Age columns are numeric
    for col in usage_cols + ['Age']:
        d[col] = pd.to_numeric(d[col], errors='coerce')

    # Keep only known categorical labels
    d['Platform'] = d['Platform'].where(d['Platform'].isin(valid_platforms))
    d['Gender'] = d['Gender'].where(d['Gender'].isin(valid_genders))
    d['Dominant_Emotion'] = d['Dominant_Emotion'].where(d['Dominant_Emotion'].isin(valid_emotions))

    # Drop any rows that became NaN during cleaning
    return d.dropna(subset=["Age", "Gender", "Platform", "Dominant_Emotion"] + usage_cols)

# Create clean splits
train_clean = clean_dataframe(train)
val_clean = clean_dataframe(val)
test_clean = clean_dataframe(test)

# ---- 2. Fit Encoders on the Union of all clean data ----
full_clean = pd.concat([train_clean, val_clean, test_clean])

le_gender = LabelEncoder().fit(full_clean["Gender"])
le_platform = LabelEncoder().fit(full_clean["Platform"])
le_target = LabelEncoder().fit(full_clean["Dominant_Emotion"])

# ---- 3. Transform and Prepare Model Inputs ----
def transform_data(d):
    X_out = d.copy()
    X_out["Gender_enc"] = le_gender.transform(d["Gender"])
    X_out["Platform_enc"] = le_platform.transform(d["Platform"])
    feature_cols = ["Age", "Gender_enc", "Platform_enc"] + usage_cols
    return X_out[feature_cols], le_target.transform(d["Dominant_Emotion"])

X_train, y_train = transform_data(train_clean)
X_val, y_val = transform_data(val_clean)
X_test, y_test = transform_data(test_clean)

print(f"Cleaned Shapes - Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")

# ---- 4. Scaling ----
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

# ---- 5. Train and compare models ----
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42, max_depth=6),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
}

results = {}
for name, model in models.items():
    if name == "Logistic Regression":
        model.fit(X_train_scaled, y_train)
        preds = model.predict(X_val_scaled)
    else:
        model.fit(X_train, y_train)
        preds = model.predict(X_val)

    acc = accuracy_score(y_val, preds)
    f1_macro = f1_score(y_val, preds, average="macro")
    results[name] = {"accuracy": acc, "f1_macro": f1_macro}
    print(f"{name}: Accuracy={acc:.3f}, Macro-F1={f1_macro:.3f}")

results_df = pd.DataFrame(results).T.sort_values("f1_macro", ascending=False)
print("\nSorted Comparison:", results_df)

# ---- 6. Final Evaluation on Test Set (Best Model: Random Forest) ----
best_rf = models['Random Forest']
# Random Forest doesn't need scaling, but we use the original X_test
test_preds = best_rf.predict(X_test)

test_acc = accuracy_score(y_test, test_preds)
test_f1 = f1_score(y_test, test_preds, average='macro')

print(f"--- Final Test Set Results (Random Forest) ---")
print(f"Accuracy: {test_acc:.3f}")
print(f"Macro-F1 Score: {test_f1:.3f}")
print("\nClassification Report:")
print(classification_report(y_test, test_preds, target_names=le_target.classes_))

# Visualize Confusion Matrix
cm = confusion_matrix(y_test, test_preds)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=le_target.classes_,
            yticklabels=le_target.classes_)
plt.title('Confusion Matrix: Random Forest (Test Set)')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

best_model_name = results_df.index[0]
print(f"Best model on validation set: {best_model_name}")

best_model = models[best_model_name]

# Final evaluation ONLY on test set (never touched until now — this is the golden rule)
if best_model_name == "Logistic Regression":
    test_preds = best_model.predict(X_test_scaled)
else:
    test_preds = best_model.predict(X_test)

print("\n=== FINAL TEST SET RESULTS ===")
print(classification_report(y_test, test_preds, target_names=le_target.classes_))

cm = confusion_matrix(y_test, test_preds)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=le_target.classes_, yticklabels=le_target.classes_)
plt.xlabel("Predicted"); plt.ylabel("Actual")
plt.title(f"Confusion Matrix — {best_model_name} (Test Set)")
plt.show()

best_model_name = results_df.index[0]
print(f"Best model on validation set: {best_model_name}")

best_model = models[best_model_name]

# Final evaluation ONLY on test set (never touched until now — this is the golden rule)
if best_model_name == "Logistic Regression":
    test_preds = best_model.predict(X_test_scaled)
else:
    test_preds = best_model.predict(X_test)

print("\n=== FINAL TEST SET RESULTS ===")
print(classification_report(y_test, test_preds, target_names=le_target.classes_))

cm = confusion_matrix(y_test, test_preds)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=le_target.classes_, yticklabels=le_target.classes_)
plt.xlabel("Predicted"); plt.ylabel("Actual")
plt.title(f"Confusion Matrix — {best_model_name} (Test Set)")
plt.show()

if best_model_name in ["Random Forest", "Gradient Boosting", "Decision Tree"]:
    importances = pd.Series(best_model.feature_importances_, index=feature_cols)
    importances = importances.sort_values(ascending=False)

    plt.figure(figsize=(8,5))
    sns.barplot(x=importances.values, y=importances.index)
    plt.title(f"Feature Importance — {best_model_name}")
    plt.xlabel("Importance")
    plt.show()

    print(importances)

from sklearn.dummy import DummyClassifier

dummy = DummyClassifier(strategy="most_frequent", random_state=42)
dummy.fit(X_train, y_train)
dummy_preds = dummy.predict(X_test)

print("Dummy baseline accuracy:", accuracy_score(y_test, dummy_preds))
print("Your model's accuracy:  ", accuracy_score(y_test, test_preds))

for name, (X_, y_, label) in {
    "train": (X_train, y_train, "Train"),
    "val": (X_val, y_val, "Validation"),
    "test": (X_test, y_test, "Test"),
}.items():
    preds_ = best_model.predict(X_ if best_model_name != "Logistic Regression" else scaler.transform(X_))
    acc_ = accuracy_score(y_, preds_)
    print(f"{label} accuracy: {acc_:.3f}")

from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(best_model, X_train, y_train, cv=5, scoring="f1_macro")
print("Cross-val Macro-F1 scores:", cv_scores.round(3))
print(f"Mean: {cv_scores.mean():.3f}  |  Std: {cv_scores.std():.3f}")

print(classification_report(y_test, test_preds, target_names=le_target.classes_))

import pandas as pd

pred_dist = pd.Series(test_preds).value_counts(normalize=True).sort_index()
actual_dist = pd.Series(y_test).value_counts(normalize=True).sort_index()

comparison = pd.DataFrame({"Actual": actual_dist, "Predicted": pred_dist})
comparison.index = le_target.classes_
print(comparison.round(3))

from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, classification_report

print("="*50)
print("CHECK 1: DUMMY BASELINE")
print("="*50)
dummy = DummyClassifier(strategy="most_frequent", random_state=42)
dummy.fit(X_train, y_train)
dummy_preds = dummy.predict(X_test)
print("Dummy baseline accuracy:", accuracy_score(y_test, dummy_preds))
print("Your model's accuracy:  ", accuracy_score(y_test, test_preds))

print("\n" + "="*50)
print("CHECK 2: TRAIN vs VAL vs TEST ACCURACY (overfitting check)")
print("="*50)
for label, X_, y_ in [("Train", X_train, y_train), ("Validation", X_val, y_val), ("Test", X_test, y_test)]:
    if best_model_name == "Logistic Regression":
        preds_ = best_model.predict(scaler.transform(X_))
    else:
        preds_ = best_model.predict(X_)
    acc_ = accuracy_score(y_, preds_)
    print(f"{label} accuracy: {acc_:.3f}")

print("\n" + "="*50)
print("CHECK 3: FULL CLASSIFICATION REPORT (test set)")
print("="*50)
print(classification_report(y_test, test_preds, target_names=le_target.classes_))